apiVersion: apps/v1
kind: Deployment
metadata:
  name: financial-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: financial-admin
  template:
    metadata:
      labels:
        app: financial-admin
    spec:
      containers:
      - name: financial-admin
        image: nginx
        ports:
        - containerPort: 80