apiVersion: apps/v1
kind: Deployment
metadata:
  name: financial-admin
  namespace: financial-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: financial-admin
  template:
    metadata:
      labels:
        app: financial-admin
    spec:
      imagePullSecrets:
        - name: acr-secret
      containers:
        - name: financial-admin
          image: crpi-4gjhfmn9d3r2c9et.cn-hangzhou.personal.cr.aliyuncs.com/financial-admin/financial-admin:c6cf35a
          ports:
            - containerPort: 80
