apiVersion: v1
kind: Service
metadata:
  name: financial-admin
  namespace: financial-admin
spec:
  type: NodePort
  selector:
    app: financial-admin
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080